# backend/build_desktop.ps1
# Builds the standalone Windows .exe for the Prompt Optimizer Agent.
# Produces backend\launcher.exe (single file, no install required).
#
# Requires: Python 3.13 (with backend deps installed) and Node.js.
# On first run Nuitka downloads a C compiler automatically (internet needed).
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File backend/build_desktop.ps1

param(
    [switch]$SkipFrontend,   # reuse an existing frontend\dist
    [switch]$SkipNuitka      # only refresh app\web + app\core\secret.py
)

$ErrorActionPreference = "Continue"
$backend  = $PSScriptRoot
$root     = (Resolve-Path (Join-Path $backend "..")).Path
$frontend = Join-Path $root "frontend"
$webDir   = Join-Path $backend "app\web"
$envFile  = Join-Path $backend ".env"

# Prefer the Python 3.12 build venv (MinGW64 GCC is supported there); the
# system Python 3.13 falls back to the broken Zig toolchain, so use 3.12.
$venvPy = Join-Path $backend ".venv312\Scripts\python.exe"
if (Test-Path $venvPy) { $py = $venvPy } else { $py = "python" }
Write-Host "Using Python: $py"

Write-Host "== 1/4 Building frontend (Vite) =="
if (-not $SkipFrontend) {
    Push-Location $frontend
    try {
        if (-not (Test-Path "node_modules")) { npm install }
        npm run build
    } finally { Pop-Location }
}

Write-Host "== 2/4 Embedding web UI into backend/app/web =="
if (-not (Test-Path (Join-Path $frontend "dist\index.html"))) {
    throw "frontend\dist\index.html not found - build the frontend first."
}
if (Test-Path $webDir) { Remove-Item -Recurse -Force $webDir }
Copy-Item -Recurse (Join-Path $frontend "dist") $webDir

Write-Host "== 3/4 Generating obfuscated key module (app/core/secret.py) =="
if (-not (Test-Path $envFile)) { throw "backend\.env not found - set API_KEY there first." }
$line = Get-Content $envFile | Where-Object { $_ -match "^API_KEY=" } | Select-Object -First 1
if (-not $line) { throw "API_KEY not found in backend\.env" }
$key = $line.Substring($line.IndexOf("=") + 1).Trim('"').Trim()
if (-not $key) { throw "API_KEY is empty in backend\.env" }
$bytes = [System.Text.Encoding]::UTF8.GetBytes($key)
$xored = [byte[]]($bytes | ForEach-Object { $_ -bxor 0x5A })
$b64   = [Convert]::ToBase64String($xored)
$secretPy = @"
# Auto-generated by build_desktop.ps1 - do not edit or commit.
import base64

_OBFUSCATED = "$b64"

def get_api_key() -> str:
    raw = base64.b64decode(_OBFUSCATED)
    return bytes(b ^ 0x5A for b in raw).decode("utf-8")
"@
Set-Content -Path (Join-Path $backend "app\core\secret.py") -Value $secretPy -Encoding UTF8

Write-Host "== 4/4 Compiling with Nuitka (onefile) =="
if (-not $SkipNuitka) {
    Push-Location $backend
    try {
        & $py -c "import importlib.util, sys; sys.exit(0 if importlib.util.find_spec('nuitka') else 1)"
        if ($LASTEXITCODE -ne 0) {
            Write-Host "Installing Nuitka..."
            & $py -m pip install nuitka
            if ($LASTEXITCODE -ne 0) { throw "Failed to install Nuitka." }
        }
        & $py -m nuitka `
            --onefile `
            --mingw64 `
            --assume-yes-for-downloads `
            --include-data-dir=app/skills=app/skills `
            --include-data-dir=app/web=app/web `
            --include-package=app `
            --include-package=tiktoken `
            --include-package=tiktoken_ext `
            --include-package-data=tiktoken `
            --include-package-data=tiktoken_ext `
            --include-package-data=certifi `
            --include-module=tiktoken_ext.openai_public `
            --windows-company-name="Prompt Optimizer" `
            --windows-product-name="AI Prompt Optimization Agent" `
            --windows-file-version="1.0.0.0" `
            launcher.py
        if ($LASTEXITCODE -ne 0) { throw "Nuitka build failed." }
    } finally { Pop-Location }
    Write-Host ""
    Write-Host "Build complete: $backend\launcher.exe"
}
