#!/usr/bin/env bash
# backend/build_desktop_mac.sh
# Builds a standalone macOS binary (onefile) for the Prompt Optimizer Agent.
# Produces backend\launcher (no install required) — same behavior as the
# Windows launcher.exe.
#
# IMPORTANT: macOS builds must run ON a Mac (no cross-compiling from Windows).
# Requires: macOS with Xcode command-line tools, Python 3.12, and Node.js.
#
# Usage:
#   bash backend/build_desktop_mac.sh
# Env overrides:
#   SKIP_FRONTEND=1   reuse an existing frontend\dist
#   SKIP_NUITKA=1     only refresh app\web + app\core\secret.py
set -euo pipefail

backend="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$backend/.." && pwd)"
frontend="$root/frontend"
webDir="$backend/app/web"
envFile="$backend/.env"

# Prefer the Python 3.12 build venv if present, else system python3.
PY="${PYTHON:-python3}"
if [ -x "$backend/.venv312/bin/python" ]; then
    PY="$backend/.venv312/bin/python"
fi
echo "Using Python: $PY"

echo "== 1/4 Building frontend (Vite) =="
if [ "${SKIP_FRONTEND:-0}" != "1" ]; then
    (
        cd "$frontend"
        [ -d node_modules ] || npm install
        npm run build
    )
fi

echo "== 2/4 Embedding web UI into backend/app/web =="
if [ ! -f "$frontend/dist/index.html" ]; then
    echo "frontend/dist/index.html not found - build the frontend first." >&2
    exit 1
fi
rm -rf "$webDir"
cp -R "$frontend/dist" "$webDir"

echo "== 3/4 Generating obfuscated key module (app/core/secret.py) =="
if [ ! -f "$envFile" ]; then
    echo "backend/.env not found - set API_KEY there first." >&2
    exit 1
fi
key="$(grep -E '^API_KEY=' "$envFile" | head -n1 | cut -d'=' -f2- | tr -d '"' | tr -d ' ')"
if [ -z "$key" ]; then
    echo "API_KEY not found in backend/.env" >&2
    exit 1
fi
b64="$("$PY" - "$key" <<'PYEOF'
import base64
import sys

key = sys.argv[1].encode("utf-8")
print(base64.b64encode(bytes(b ^ 0x5A for b in key)).decode("ascii"))
PYEOF
)"
cat > "$backend/app/core/secret.py" <<EOF
# Auto-generated by build_desktop_mac.sh - do not edit or commit.
import base64

_OBFUSCATED = "$b64"

def get_api_key() -> str:
    raw = base64.b64decode(_OBFUSCATED)
    return bytes(b ^ 0x5A for b in raw).decode("utf-8")
EOF

echo "== 4/4 Compiling with Nuitka (onefile) =="
if [ "${SKIP_NUITKA:-0}" != "1" ]; then
    (
        cd "$backend"
        "$PY" -c "import importlib.util, sys; sys.exit(0 if importlib.util.find_spec('nuitka') else 1)" \
            || { echo "Installing Nuitka..."; "$PY" -m pip install nuitka; }
        "$PY" -m nuitka \
            --onefile \
            --macos-app-name="AI Prompt Optimization Agent" \
            --macos-app-version="1.0.0" \
            --include-data-dir=app/skills=app/skills \
            --include-data-dir=app/web=app/web \
            --include-package=app \
            --include-package=tiktoken \
            --include-package=tiktoken_ext \
            --include-package-data=tiktoken \
            --include-package-data=tiktoken_ext \
            --include-package-data=certifi \
            --include-module=tiktoken_ext.openai_public \
            launcher.py
    )
    echo ""
    echo "Build complete: $backend/launcher"
fi
